services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9  # Use a version that matches your local setup
      - key: TELEGRAM_BOT_TOKEN
        fromEnv: TELEGRAM_BOT_TOKEN
      - key: GROQ_API_KEY
        fromEnv: GROQ_API_KEY
    disk:
      name: bot-storage
      mountPath: /opt/render/project/src/downloads
      sizeGB: 1
